import type { AuditLog, Candidate, Dashboard, Decision, Experiment, NationalMode, Node, NodeMetric, Plan, Route, Subscription, SystemSetting, TelemetryPoint, TokenPair, TrafficBreakdown, User } from './types'

const base = import.meta.env.VITE_API_URL ?? ''
const ACCESS_KEY = 'pars2ray.access'
const REFRESH_KEY = 'pars2ray.refresh'
const MOCK_KEY = 'pars2ray.mock'
const MOCK_ENABLED = import.meta.env.VITE_ENABLE_MOCK_MODE === '1'
let access = localStorage.getItem(ACCESS_KEY) ?? ''
let refresh = localStorage.getItem(REFRESH_KEY) ?? ''
let refreshRequest: Promise<boolean> | null = null
export const isMockMode = () => MOCK_ENABLED && localStorage.getItem(MOCK_KEY) === '1'
export const setMockMode = (enabled: boolean) => enabled && MOCK_ENABLED ? localStorage.setItem(MOCK_KEY, '1') : localStorage.removeItem(MOCK_KEY)
export function setSession(tokens: TokenPair) { access = tokens.access_token; refresh = tokens.refresh_token; localStorage.setItem(ACCESS_KEY, access); localStorage.setItem(REFRESH_KEY, refresh) }
export function clearSession() { access = ''; refresh = ''; localStorage.removeItem(ACCESS_KEY); localStorage.removeItem(REFRESH_KEY) }
export function hasAccess() { return isMockMode() || Boolean(access) }
const mockNow = () => new Date().toISOString()
const mockNodes: Node[] = [{ id:1,node_key:'demo-node-01',country:'Germany',endpoint:'203.0.113.10:443',status:'online',score:96.4,cpu_percent:24,memory_percent:41,traffic_rx_bytes:1840000000,traffic_tx_bytes:920000000,latency_ms:38,core:'xray',core_version:'25.8.3',agent_version:'2.2.0',capabilities:{reality:true,grpc:true},last_seen_at:mockNow(),created_at:mockNow() }]
const mockDashboard: Dashboard = { node_count:1,online_nodes:1,network_health:96,traffic:{rx_bytes:1840000000,tx_bytes:920000000},current_best_route:'',ai_status:'ready',mode:'LIVE',user_count:0,subscription_count:0 }
const mockRoutes: Route[] = []
const mockTelemetry: TelemetryPoint[] = []
const mockBreakdown: TrafficBreakdown[] = []
export const mockTokenPair: TokenPair = { access_token:'mock-access-token',refresh_token:'mock-refresh-token',token_type:'bearer',expires_in:86400 }
async function renew(): Promise<boolean> { if(isMockMode()) return true;if(!refresh)return false;if(!refreshRequest) refreshRequest=fetch(`${base}/api/v1/auth/refresh`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({refresh_token:refresh})}).then(async response=>{if(!response.ok)return false;setSession(await response.json() as TokenPair);return true}).catch(()=>false).finally(()=>{refreshRequest=null});return refreshRequest }
async function request<T>(path:string,options:RequestInit={},retried=false):Promise<T>{if(isMockMode())return mockRequest<T>(path,options);const response=await fetch(`${base}${path}`,{...options,headers:{'Content-Type':'application/json',...(access?{Authorization:`Bearer ${access}`}:{}) ,...(options.headers??{})}});if(response.status===401&&!retried&&await renew())return request<T>(path,options,true);if(response.status===401)clearSession();if(!response.ok){const body=await response.json().catch(()=>({detail:response.statusText})) as {detail?:string};throw new Error(typeof body.detail==='string'?body.detail:JSON.stringify(body.detail??`request_failed_${response.status}`))}if(response.status===204)return undefined as T;return response.json() as Promise<T>}
async function mockRequest<T>(path:string,options:RequestInit):Promise<T>{await new Promise(resolve=>window.setTimeout(resolve,50));if(path==='/api/v1/auth/login')return mockTokenPair as T;if(path==='/api/v1/auth/logout'){setMockMode(false);clearSession();return {ok:true} as T}if(path==='/api/v1/dashboard')return mockDashboard as T;if(path.startsWith('/api/v1/dashboard/telemetry'))return mockTelemetry as unknown as T;if(path.startsWith('/api/v1/dashboard/traffic-breakdown'))return mockBreakdown as unknown as T;if(path==='/api/v1/nodes')return mockNodes as T;if(path.startsWith('/api/v1/nodes/')&&path.endsWith('/metrics'))return mockNodes.slice(0,1).map((n,i)=>({id:i+1,latency_ms:n.latency_ms,jitter_ms:3.2,packet_loss_percent:.4,throughput_mbps:840,cpu_percent:n.cpu_percent,memory_percent:n.memory_percent,stability_percent:n.score,measured_at:mockNow()})) as unknown as T;if(path==='/api/v1/routes')return mockRoutes as unknown as T;if(path.startsWith('/api/v1/national-mode'))return {mode:'LIVE',failures:0,successes:100} as T;if(path==='/api/v1/experiments')return [] as unknown as T;if(path==='/api/v1/optimizer/decisions')return [] as unknown as T;if(path==='/api/v1/optimizer/candidates')return {candidates:[],mode:'LIVE'} as T;if(path==='/api/v1/users')return [] as unknown as T;if(path==='/api/v1/plans')return [] as unknown as T;if(path==='/api/v1/subscriptions'&&options.method==='POST')return {id:1,token:'mock-subscription-token',expires_at:new Date(Date.now()+30*86400000).toISOString(),node_keys:[]} as T;if(path==='/api/v1/subscriptions')return [] as unknown as T;if(path==='/api/v1/system/settings')return [] as unknown as T;if(path==='/api/v1/system/panel-domain')return {domain:'',tls:true,email:''} as T;if(path==='/api/v1/system/subscription-html')return {html:'<!doctype html><html><body>{{configs}}</body></html>'} as T;if(path==='/api/v1/optimizer/decisions')return [] as unknown as T;if(options.method==='DELETE')return {ok:true} as T;if(options.method==='POST'||options.method==='PATCH'||options.method==='PUT')return {ok:true} as T;return {} as T}
export const api={
 login:async(username:string,password:string)=>request<TokenPair>('/api/v1/auth/login',{method:'POST',body:JSON.stringify({username,password})}),logout:()=>request<{ok:boolean}>('/api/v1/auth/logout',{method:'POST',body:JSON.stringify({refresh_token:refresh})}).finally(clearSession),dashboard:()=>request<Dashboard>('/api/v1/dashboard'),telemetry:(hours=24)=>request<TelemetryPoint[]>(`/api/v1/dashboard/telemetry?hours=${hours}`),trafficBreakdown:(hours=24)=>request<TrafficBreakdown[]>(`/api/v1/dashboard/traffic-breakdown?hours=${hours}`),nodes:()=>request<Node[]>('/api/v1/nodes'),
 testSSH:(payload:{host:string;username:string;password:string})=>request<{ok:boolean;output:string}>('/api/v1/node-management/test-ssh',{method:'POST',body:JSON.stringify(payload)}),provisionNode:(payload:{node_key:string;country:string;ssh:{host:string;username:string;password:string}})=>request<{id:number;node_key:string;country:string;status:string;provisioned:boolean}>('/api/v1/node-management',{method:'POST',body:JSON.stringify(payload)}),nodeMetrics:(nodeKey:string,limit=60)=>request<NodeMetric[]>(`/api/v1/nodes/${nodeKey}/metrics?limit=${limit}`),coreStatus:(nodeKey:string)=>request<Record<string,unknown>>(`/api/v1/nodes/${nodeKey}/core-status`),
 users:()=>request<User[]>('/api/v1/users'),createUser:(payload:Record<string,unknown>)=>request<User>('/api/v1/users',{method:'POST',body:JSON.stringify(payload)}),updateUser:(id:number,payload:Record<string,unknown>)=>request<User>(`/api/v1/users/${id}`,{method:'PATCH',body:JSON.stringify(payload)}),auditLogs:()=>request<AuditLog[]>('/api/v1/audit-logs'),settings:()=>request<SystemSetting[]>('/api/v1/system/settings'),updateSetting:(key:string,value:string)=>request<{ok:boolean}>(`/api/v1/system/settings/${encodeURIComponent(key)}`,{method:'PUT',body:JSON.stringify({value})}),panelDomain:()=>request<{domain:string;tls:boolean;email?:string}>('/api/v1/system/panel-domain'),updatePanelDomain:(payload:{domain:string;tls:boolean;email?:string})=>request<{ok:boolean;url?:string}>('/api/v1/system/panel-domain',{method:'PUT',body:JSON.stringify(payload)}),subscriptionHtml:()=>request<{html:string}>('/api/v1/system/subscription-html'),updateSubscriptionHtml:(html:string)=>request<{ok:boolean}>('/api/v1/system/subscription-html',{method:'PUT',body:JSON.stringify({html})}),nationalMode:()=>request<NationalMode>('/api/v1/national-mode'),createApiKey:(name:string,scopes:string[])=>request<{key:string;warning:string}>('/api/v1/api-keys',{method:'POST',body:JSON.stringify({name,scopes})}),
 aiInboundRecommendations:(limit=12)=>request<{candidates:Array<Record<string,unknown>>;generated_at:string}>(`/api/v1/ai/inbounds/recommendations?limit=${limit}`),selectAiInbound:(payload:Record<string,unknown>)=>request<Record<string,unknown>>('/api/v1/ai/inbounds/select',{method:'POST',body:JSON.stringify(payload)}),inbounds:()=>request<Array<Record<string,unknown>>>('/api/v1/inbounds'),clientUsers:()=>request<Array<Record<string,unknown>>>('/api/v1/users/clients'),createClientUser:(payload:Record<string,unknown>)=>request<Record<string,unknown>>('/api/v1/users/clients',{method:'POST',body:JSON.stringify(payload)}),deleteClientUser:(id:number)=>request<{ok:boolean}>(`/api/v1/users/clients/${id}`,{method:'DELETE'}),decisions:()=>request<Decision[]>('/api/v1/optimizer/decisions'),buildRouteConfig:(routeId:number,payload:{apply:boolean})=>request<{config:unknown}>(`/api/v1/routes/${routeId}/config`,{method:'POST',body:JSON.stringify(payload)})
}
