import { useEffect, useMemo, useState } from 'react'
import { api, hasAccess } from './api'
import type { Dashboard, Node, Page, Route } from './types'

const pages: Page[] = ['Dashboard', 'Nodes', 'Routes', 'Protocols', 'Experiments', 'Optimizer', 'Users', 'Subscriptions', 'Billing', 'Settings']
const icons: Record<Page, string> = { Dashboard: '▦', Nodes: '◇', Routes: '⌁', Protocols: '◌', Experiments: '◎', Optimizer: '✦', Users: '♙', Subscriptions: '▤', Billing: '◫', Settings: '⚙' }

function fmtBytes(value: number) { if (!value) return '0 B'; const units = ['B', 'KB', 'MB', 'GB', 'TB']; const i = Math.min(Math.floor(Math.log(value) / Math.log(1024)), units.length - 1); return `${(value / 1024 ** i).toFixed(i ? 1 : 0)} ${units[i]}` }
function Badge({ value }: { value: string }) { return <span className={`badge ${value.toLowerCase().replaceAll('_', '-')}`}>{value.replaceAll('_', ' ')}</span> }
function MetricCard({ label, value, hint, accent }: { label: string; value: string | number; hint: string; accent: string }) { return <div className="metric-card"><div className="metric-top"><span>{label}</span><i style={{ background: accent }} /></div><strong>{value}</strong><small>{hint}</small></div> }

export default function App() {
  const [page, setPage] = useState<Page>('Dashboard')
  const [dashboard, setDashboard] = useState<Dashboard | null>(null)
  const [nodes, setNodes] = useState<Node[]>([])
  const [routes, setRoutes] = useState<Route[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const authed = hasAccess()

  useEffect(() => { if (!authed) { setLoading(false); return } void Promise.all([api.dashboard(), api.nodes(), api.routes()]).then(([d, n, r]) => { setDashboard(d); setNodes(n); setRoutes(r) }).catch(e => setError(e.message)).finally(() => setLoading(false)) }, [authed])
  const onlinePercent = useMemo(() => dashboard && dashboard.node_count ? Math.round(dashboard.online_nodes / dashboard.node_count * 100) : 0, [dashboard])

  if (!authed) return <Login />
  return <div className="shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">P</span><div><strong>Pars2Ray</strong><small>ENTERPRISE CONTROL</small></div></div><nav>{pages.map(item => <button key={item} className={page === item ? 'nav-item active' : 'nav-item'} onClick={() => setPage(item)}><span>{icons[item]}</span>{item}</button>)}</nav><div className="side-footer"><div className="connection"><span className="live-dot" /> Master online</div><small>v2.0.0 · Production</small></div></aside><main className="main"><header className="topbar"><div><span className="eyebrow">CONTROL PLANE / {page.toUpperCase()}</span><h1>{page}</h1></div><div className="top-actions"><span className="mode"><i className="live-dot" /> {dashboard?.mode ?? 'NORMAL'}</span><button className="icon-button" aria-label="Notifications">♢</button><div className="avatar">SA</div></div></header>{error && <div className="error-banner">{error}</div>}{loading ? <div className="loading">Loading control plane…</div> : page === 'Dashboard' ? <DashboardView dashboard={dashboard} nodes={nodes} onlinePercent={onlinePercent} /> : page === 'Nodes' ? <NodesView nodes={nodes} refresh={() => api.nodes().then(setNodes)} /> : page === 'Routes' ? <RoutesView routes={routes} /> : <GenericView page={page} />}</main></div>
}

function Login() { return <div className="login-page"><div className="login-card"><div className="brand"><span className="brand-mark">P</span><div><strong>Pars2Ray</strong><small>ENTERPRISE CONTROL</small></div></div><h1>Sign in</h1><p>Control plane access</p><form onSubmit={e => { e.preventDefault(); const form = new FormData(e.currentTarget); void fetch('/api/v1/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username: form.get('username'), password: form.get('password') }) }).then(r => r.json()).then(data => { if (data.access_token) { localStorage.setItem('pars2ray.access', data.access_token); location.reload() } else alert(data.detail ?? 'Sign in failed') }) }}><label>Username<input name="username" autoComplete="username" required /></label><label>Password<input name="password" type="password" autoComplete="current-password" required /></label><button className="primary wide">Sign in</button></form><small className="login-note">Authorized operators only</small></div></div> }
function DashboardView({ dashboard, nodes, onlinePercent }: { dashboard: Dashboard | null; nodes: Node[]; onlinePercent: number }) { if (!dashboard) return <Empty />; return <><section className="metrics-grid"><MetricCard label="Nodes" value={`${dashboard.online_nodes}/${dashboard.node_count}`} hint={`${onlinePercent}% online`} accent="#36d399" /><MetricCard label="Network health" value={`${dashboard.network_health.toFixed(1)}%`} hint="Weighted live score" accent="#5b8cff" /><MetricCard label="Traffic" value={fmtBytes(dashboard.traffic.rx_bytes + dashboard.traffic.tx_bytes)} hint="Aggregate counters" accent="#b98cff" /><MetricCard label="AI status" value={dashboard.ai_status} hint="Decision gateway" accent="#f7b955" /></section><section className="content-grid"><div className="panel"><div className="panel-head"><div><span className="eyebrow">LIVE INVENTORY</span><h2>Node health</h2></div><button className="ghost">View all</button></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Country</th><th>Status</th><th>CPU</th><th>RAM</th><th>Traffic</th><th>Score</th></tr></thead><tbody>{nodes.slice(0, 6).map(node => <tr key={node.node_key}><td className="strong">{node.node_key}</td><td><span className="country">{node.country}</span></td><td><Badge value={node.status} /></td><td><Progress value={node.cpu_percent} /></td><td><Progress value={node.memory_percent} /></td><td>{fmtBytes(node.traffic_rx_bytes + node.traffic_tx_bytes)}</td><td className="score">{node.score.toFixed(1)}</td></tr>)}</tbody></table>{!nodes.length && <Empty />}</div></div><div className="panel route-panel"><div className="panel-head"><div><span className="eyebrow">OPTIMIZER</span><h2>Route posture</h2></div><span className="status-indicator"><i className="live-dot" /> Protected</span></div><div className="route-score"><div className="score-ring"><strong>{dashboard.network_health.toFixed(0)}</strong><span>score</span></div><div><h3>{dashboard.current_best_route ?? 'No active route'}</h3><p>Current best route</p><Badge value={dashboard.mode} /></div></div><div className="mini-stat"><span>Fallback mode</span><strong>{dashboard.mode === 'NORMAL' ? 'Standby' : 'Active'}</strong></div><div className="mini-stat"><span>Subscriptions</span><strong>{dashboard.subscription_count}</strong></div></div></section></> }
function NodesView({ nodes, refresh }: { nodes: Node[]; refresh: () => Promise<Node[]> }) { return <section className="panel page-panel"><div className="panel-head"><div><span className="eyebrow">INFRASTRUCTURE</span><h2>Managed nodes</h2></div><button className="primary" onClick={() => void refresh()}>Refresh</button></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Country</th><th>Status</th><th>CPU</th><th>RAM</th><th>Traffic</th><th>Score</th><th>Actions</th></tr></thead><tbody>{nodes.map(node => <tr key={node.node_key}><td className="strong">{node.node_key}</td><td><span className="country">{node.country}</span></td><td><Badge value={node.status} /></td><td>{node.cpu_percent.toFixed(1)}%</td><td>{node.memory_percent.toFixed(1)}%</td><td>{fmtBytes(node.traffic_rx_bytes + node.traffic_tx_bytes)}</td><td className="score">{node.score.toFixed(1)}</td><td><div className="row-actions"><button className="small-action" onClick={() => alert(`${node.node_key} · ${node.core}`)}>View</button><button className="small-action" onClick={() => void api.command(node.node_key, 'benchmark')}>Benchmark</button><button className="small-action" onClick={() => void api.command(node.node_key, 'restart')}>Restart</button><button className="small-action" onClick={() => void api.command(node.node_key, 'drain')}>Drain</button><button className="small-action" onClick={() => void api.command(node.node_key, 'rollback')}>Rollback</button><button className="small-action" onClick={() => void api.remove(node.node_key).then(() => void refresh())}>Remove</button></div></td></tr>)}</tbody></table>{!nodes.length && <Empty />}</div></section> }
function RoutesView({ routes }: { routes: Route[] }) { return <section className="panel page-panel"><div className="panel-head"><div><span className="eyebrow">TRAFFIC ENGINEERING</span><h2>Routes</h2></div><button className="primary">Create route</button></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Protocol</th><th>Transport</th><th>Core</th><th>Status</th><th>Score</th><th>Wins</th></tr></thead><tbody>{routes.map(route => <tr key={route.id}><td className="strong">{route.name}</td><td>{route.protocol}</td><td>{route.transport}</td><td>{route.core}</td><td><Badge value={route.status} /></td><td className="score">{route.score.toFixed(1)}</td><td>{route.consecutive_wins}</td></tr>)}</tbody></table>{!routes.length && <Empty />}</div></section> }
function GenericView({ page }: { page: Page }) { return <section className="panel page-panel empty-page"><div className="empty-icon">{icons[page]}</div><h2>{page}</h2><p>Connected to the Pars2Ray control plane.</p><button className="primary">Open {page.toLowerCase()}</button></section> }
function Progress({ value }: { value: number }) { return <div className="progress"><span style={{ width: `${Math.min(value, 100)}%` }} /></div> }
function Empty() { return <div className="empty">No records available</div> }
