import { useEffect, useRef, useState, type FormEvent } from 'react'
import { api } from './api'
import type { Locale, Node } from './types'
import { Field, Icon, Modal, Panel, type T } from './ui'

type Notify=(message:string,kind?:'success'|'error')=>void
type Props={t:T;locale:Locale;notify:Notify;nodes:Node[];reload:()=>Promise<void>}
const finite=(value:unknown,fallback=0)=>{const n=Number(value);return Number.isFinite(n)?n:fallback}
const safe=(value:unknown,fallback='—')=>value===null||value===undefined||value===''?fallback:String(value)

export function NodeProvisionPage({t,notify,nodes,reload}:Props){
 const [show,setShow]=useState(false);const [testing,setTesting]=useState(false);const [creating,setCreating]=useState(false);const [busy,setBusy]=useState<string|null>(null);const [selected,setSelected]=useState<Node|null>(null);const [editCountry,setEditCountry]=useState('');const formRef=useRef<HTMLFormElement>(null)
 useEffect(()=>{const timer=window.setInterval(()=>{void reload().catch(()=>undefined)},30000);return()=>window.clearInterval(timer)},[reload])
 useEffect(()=>{if(selected)setEditCountry(selected.country)},[selected?.id])
 async function testSSH(){const form=formRef.current;if(!form)return;setTesting(true);const data=new FormData(form);try{await api.testSSH({host:String(data.get('host')).trim(),port:finite(data.get('port'),22),username:String(data.get('username')).trim(),password:String(data.get('password')||'')});notify(t('completed'))}catch(error){notify(error instanceof Error?error.message:t('failed'),'error')}finally{setTesting(false)}}
 async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setCreating(true);const form=new FormData(event.currentTarget);try{await api.provisionNode({node_key:String(form.get('node_key')).trim().toUpperCase(),country:String(form.get('country')).trim().toUpperCase(),ssh:{host:String(form.get('host')).trim(),port:finite(form.get('port'),22),username:String(form.get('username')).trim(),password:String(form.get('password')||'')}});notify(t('completed'));setShow(false);await reload()}catch(error){notify(error instanceof Error?error.message:t('failed'),'error')}finally{setCreating(false)}}
 async function action(node:Node,kind:'probe'|'restart'|'drain'|'rollback'|'delete'){setBusy(`${node.node_key}:${kind}`);try{if(kind==='probe')await api.probeNode(node.node_key);else if(kind==='restart')await api.restartNode(node.node_key);else if(kind==='drain')await api.drainNode(node.node_key);else if(kind==='rollback')await api.rollbackNode(node.node_key);else {await api.deleteNode(node.node_key);setSelected(null)}notify(t('completed'));await reload()}catch(error){notify(error instanceof Error?error.message:t('failed'),'error')}finally{setBusy(null)}}
 async function saveEdit(){if(!selected)return;setBusy(`${selected.node_key}:edit`);try{await api.updateNode(selected.node_key,{country:editCountry.trim().toUpperCase()});notify(t('completed'));setSelected(null);await reload()}catch(error){notify(error instanceof Error?error.message:t('failed'),'error')}finally{setBusy(null)}}
 return <Panel title={t('managedNodes')} eyebrow="INFRASTRUCTURE" className="page-panel" action={<button className="button primary" onClick={()=>setShow(true)}><Icon name="plus" size={15}/>{t('create')}</button>}>
  {nodes.length===0?<div className="empty-state"><strong>No nodes configured</strong><span>Add a node to begin health monitoring and AI inbound generation.</span><button className="button primary" onClick={()=>setShow(true)}>Add node</button></div>:<div className="table-scroll"><table><thead><tr><th>Node</th><th>Country</th><th>Status</th><th>Core</th><th>Latency</th><th>Score</th><th>Actions</th></tr></thead><tbody>{nodes.map(node=><tr key={node.id}><td><button className="link-button" onClick={()=>setSelected(node)}><strong>{safe(node.node_key)}</strong></button></td><td>{safe(node.country)}</td><td>{safe(node.status)}</td><td>{safe(node.core)}</td><td>{finite(node.latency_ms).toFixed(0)} ms</td><td>{finite(node.score).toFixed(1)}</td><td><div className="inline-actions"><button className="button ghost" disabled={busy!==null} onClick={()=>void action(node,'probe')}>{busy===`${node.node_key}:probe`?'Checking…':'Check'}</button><button className="button ghost" disabled={busy!==null} onClick={()=>void action(node,'restart')}>Restart</button><button className="button ghost" disabled={busy!==null} onClick={()=>void action(node,'drain')}>Drain</button><button className="button ghost" disabled={busy!==null} onClick={()=>void action(node,'rollback')}>Rollback</button><button className="button ghost" disabled={busy!==null} onClick={()=>{if(window.confirm(`Delete ${node.node_key}?`))void action(node,'delete')}}>Delete</button></div></td></tr>)}</tbody></table></div>}
  {selected&&<Modal title={selected.node_key} onClose={()=>setSelected(null)} wide><div className="modal-body form-grid"><Field label="Country"><input value={editCountry} maxLength={2} onChange={event=>setEditCountry(event.target.value)}/></Field><Field label="Management"><input value="SSH managed — endpoint is internal" readOnly/></Field><Field label="Status"><input value={safe(selected.status)} readOnly/></Field><Field label="Core"><input value={safe(selected.core)} readOnly/></Field><Field label="Core version"><input value={safe(selected.core_version)} readOnly/></Field><Field label="Agent version"><input value={safe(selected.agent_version)} readOnly/></Field><Field label="Latency"><input value={`${finite(selected.latency_ms).toFixed(0)} ms`} readOnly/></Field><Field label="CPU"><input value={`${finite(selected.cpu_percent).toFixed(1)}%`} readOnly/></Field><Field label="Memory"><input value={`${finite(selected.memory_percent).toFixed(1)}%`} readOnly/></Field><Field label="Capabilities" className="span-2"><textarea value={JSON.stringify(selected.capabilities??{},null,2)} readOnly rows={6}/></Field><div className="form-actions span-2"><button className="button ghost" disabled={busy!==null} onClick={()=>void action(selected,'probe')}>Test connectivity</button><button className="button ghost" disabled={busy!==null} onClick={()=>void action(selected,'restart')}>Restart</button><button className="button primary" disabled={busy!==null} onClick={()=>void saveEdit()}>{busy===`${selected.node_key}:edit`?'Saving…':'Save changes'}</button></div></div></Modal>}
  {show&&<Modal title={t('create')} onClose={()=>setShow(false)} wide><form ref={formRef} className="modal-body form-grid" onSubmit={create}><Field label={t('name')}><input name="node_key" placeholder="DE1" pattern="[A-Za-z]{2}[0-9]{0,3}" required autoFocus/></Field><Field label={t('country')}><input name="country" placeholder="DE" minLength={2} maxLength={2} required/></Field><Field label="SSH IP / HOST" className="span-2"><input name="host" placeholder="203.0.113.10" required/></Field><Field label="SSH PORT"><input name="port" type="number" min={1} max={65535} defaultValue={22} required/></Field><Field label="SSH USER"><input name="username" placeholder="root" required/></Field><Field label="SSH PASSWORD"><input name="password" type="password" autoComplete="new-password" required/></Field><div className="form-actions span-2"><button type="button" className="button ghost" disabled={testing||creating} onClick={()=>void testSSH()}>{testing?'Testing…':'Test SSH'}</button><button type="button" className="button ghost" onClick={()=>setShow(false)}>{t('cancel')}</button><button className="button primary" disabled={creating}>{creating?'Provisioning…':'Provision & Install Agent'}</button></div></form></Modal>}
 </Panel>
}
