import { useEffect, useMemo, useState, type CSSProperties, type FormEvent } from 'react'
import { api } from './api'
import type { AuditLog, Candidate, Dashboard, Decision, Experiment, Locale, NationalMode, Node, NodeMetric, Plan, Route, Subscription, SystemSetting, TelemetryPoint, User } from './types'
import { Badge, Confirm, Empty, Field, formatBytes, formatDate, Icon, LineChart, MetricCard, Modal, Panel, Progress, Spinner, ago, type T } from './ui'

type Notify = (message: string, kind?: 'success' | 'error') => void
type Common = { t: T; locale: Locale; notify: Notify }

export function DashboardPage({ t, locale, dashboard, nodes, routes, telemetry, openPage }: Common & { dashboard: Dashboard; nodes: Node[]; routes: Route[]; telemetry: TelemetryPoint[]; openPage: (page: 'nodes' | 'routes') => void }) {
  const onlinePercent = dashboard.node_count ? Math.round(dashboard.online_nodes / dashboard.node_count * 100) : 0
  const active = routes.find(route => route.is_active)
  return <>
    <div className="metric-grid">
      <MetricCard label={t('totalNodes')} value={dashboard.node_count} hint={`${onlinePercent}% ${t('live')}`} tone="green" icon="nodes" />
      <MetricCard label={t('networkHealth')} value={`${dashboard.network_health.toFixed(1)}%`} hint={t('live')} tone="blue" icon="dashboard" />
      <MetricCard label={t('totalTraffic')} value={formatBytes(dashboard.traffic.rx_bytes + dashboard.traffic.tx_bytes)} hint="RX + TX" tone="violet" icon="routes" />
      <MetricCard label={t('activeSubscriptions')} value={dashboard.subscription_count} hint={dashboard.ai_status} tone="amber" icon="subscriptions" />
    </div>
    <div className="dashboard-grid">
      <Panel title={t('networkTraffic')} eyebrow="24H TELEMETRY" className="chart-panel" action={<div className="chart-legend"><span className="rx">RX</span><span className="tx">TX</span></div>}>
        <div className="chart-summary"><div><strong>{formatBytes(telemetry.reduce((sum, point) => sum + point.rx_bytes, 0))}</strong><span>RX</span></div><div><strong>{formatBytes(telemetry.reduce((sum, point) => sum + point.tx_bytes, 0))}</strong><span>TX</span></div></div>
        {telemetry.length ? <><LineChart values={telemetry.map(point => point.rx_bytes)} secondary={telemetry.map(point => point.tx_bytes)} /><div className="chart-axis"><span>{telemetry[0]?.timestamp ? formatDate(telemetry[0].timestamp, locale) : ''}</span><span>{telemetry.at(-1)?.timestamp ? formatDate(telemetry.at(-1)!.timestamp, locale) : ''}</span></div></> : <Empty t={t} />}
      </Panel>
      <Panel title={t('routePosture')} eyebrow="OPTIMIZER" className="posture-panel" action={<Badge value={dashboard.mode} />}>
        <div className="health-gauge" style={{ '--health': `${dashboard.network_health * 3.6}deg` } as CSSProperties}><div><strong>{dashboard.network_health.toFixed(0)}</strong><span>/ 100</span></div></div>
        <div className="active-route"><span>{t('currentBestRoute')}</span><strong>{active?.name ?? dashboard.current_best_route ?? t('noActiveRoute')}</strong>{active && <small>{active.protocol} · {active.transport} · {active.core}</small>}</div>
        <button className="button subtle wide" onClick={() => openPage('routes')}>{t('view')} <span>→</span></button>
      </Panel>
      <Panel title={t('nodeHealth')} eyebrow="LIVE INVENTORY" className="wide-panel" action={<button className="button ghost" onClick={() => openPage('nodes')}>{t('view')}</button>}>
        <div className="table-scroll"><table><thead><tr><th>{t('name')}</th><th>{t('country')}</th><th>{t('status')}</th><th>{t('cpu')}</th><th>{t('memory')}</th><th>{t('latency')}</th><th>{t('score')}</th></tr></thead><tbody>{nodes.slice(0, 7).map(node => <tr key={node.id}><td><div className="identity"><span className="node-dot">{node.country}</span><strong>{node.node_key}</strong></div></td><td>{node.country}</td><td><Badge value={node.status} /></td><td><div className="progress-cell"><Progress value={node.cpu_percent} warn /><span>{node.cpu_percent.toFixed(0)}%</span></div></td><td><div className="progress-cell"><Progress value={node.memory_percent} warn /><span>{node.memory_percent.toFixed(0)}%</span></div></td><td>{node.latency_ms ? `${node.latency_ms.toFixed(0)} ms` : '—'}</td><td><span className="score-value">{node.score.toFixed(1)}</span></td></tr>)}</tbody></table></div>{!nodes.length && <Empty t={t} />}
      </Panel>
    </div>
  </>
}

export function NodesPage({ t, locale, notify, nodes, reload }: Common & { nodes: Node[]; reload: () => Promise<void> }) {
  const [query, setQuery] = useState('')
  const [status, setStatus] = useState('ALL')
  const [selected, setSelected] = useState<Node | null>(null)
  const [metrics, setMetrics] = useState<NodeMetric[]>([])
  const [pending, setPending] = useState<{ action: string; node: Node; destructive?: boolean } | null>(null)
  const filtered = nodes.filter(node => (status === 'ALL' || node.status === status) && `${node.node_key} ${node.country} ${node.endpoint}`.toLowerCase().includes(query.toLowerCase()))

  async function inspect(node: Node) {
    setSelected(node); setMetrics([])
    try { setMetrics(await api.nodeMetrics(node.node_key)) } catch { /* Older masters may not expose metric history. */ }
  }
  async function execute() {
    if (!pending) return
    try {
      if (pending.action === 'remove') await api.removeNode(pending.node.node_key)
      else await api.command(pending.node.node_key, pending.action)
      notify(`${pending.node.node_key}: ${t('completed')}`); await reload()
    } catch (error) { notify(error instanceof Error ? error.message : t('failed'), 'error') }
  }
  return <>
    <Panel title={t('managedNodes')} eyebrow="INFRASTRUCTURE" className="page-panel" action={<div className="toolbar"><div className="search-box"><Icon name="search" size={15}/><input value={query} onChange={event => setQuery(event.target.value)} placeholder={t('search')} /></div><select value={status} onChange={event => setStatus(event.target.value)}><option value="ALL">{t('allStatuses')}</option>{['ONLINE','REGISTERED','OFFLINE','DRAINING'].map(value => <option key={value}>{value}</option>)}</select><button className="button ghost" onClick={() => void reload()}><Icon name="refresh" size={15}/>{t('refresh')}</button></div>}>
      <div className="table-scroll"><table><thead><tr><th>{t('name')}</th><th>{t('country')}</th><th>{t('status')}</th><th>{t('cpu')}</th><th>{t('memory')}</th><th>{t('traffic')}</th><th>{t('score')}</th><th>{t('lastSeen')}</th><th>{t('actions')}</th></tr></thead><tbody>{filtered.map(node => <tr key={node.id}><td><div className="identity"><span className="node-dot">{node.country}</span><div><strong>{node.node_key}</strong><small>{node.core} {node.core_version}</small></div></div></td><td>{node.country}</td><td><Badge value={node.status}/></td><td>{node.cpu_percent.toFixed(1)}%</td><td>{node.memory_percent.toFixed(1)}%</td><td>{formatBytes(node.traffic_rx_bytes + node.traffic_tx_bytes)}</td><td><span className="score-value">{node.score.toFixed(1)}</span></td><td title={formatDate(node.last_seen_at, locale)}>{ago(node.last_seen_at, locale)}</td><td><div className="row-actions"><button onClick={() => void inspect(node)}>{t('view')}</button><button onClick={() => setPending({ action: 'benchmark', node })}>{t('benchmark')}</button><details><summary><Icon name="more" size={16}/></summary><div className="action-menu"><button onClick={() => setPending({ action: 'restart', node })}>{t('restart')}</button><button onClick={() => setPending({ action: 'drain', node })}>{t('drain')}</button><button onClick={() => setPending({ action: 'rollback', node })}>{t('rollback')}</button><button className="text-danger" onClick={() => setPending({ action: 'remove', node, destructive: true })}>{t('remove')}</button></div></details></div></td></tr>)}</tbody></table></div>{!filtered.length && <Empty t={t}/>} 
    </Panel>
    {selected && <Modal title={selected.node_key} onClose={() => setSelected(null)} wide><div className="drawer-grid"><section className="detail-list"><div><span>{t('status')}</span><Badge value={selected.status}/></div><div><span>{t('endpoint')}</span><code>{selected.endpoint}</code></div><div><span>{t('core')}</span><strong>{selected.core} {selected.core_version}</strong></div><div><span>{t('agent')}</span><strong>{selected.agent_version}</strong></div><div><span>{t('lastSeen')}</span><strong>{formatDate(selected.last_seen_at, locale)}</strong></div><div><span>{t('capabilities')}</span><strong>{Object.keys(selected.capabilities ?? {}).join(', ') || '—'}</strong></div></section><section className="metric-detail"><div className="detail-kpis"><div><strong>{selected.cpu_percent.toFixed(1)}%</strong><span>{t('cpu')}</span></div><div><strong>{selected.memory_percent.toFixed(1)}%</strong><span>{t('memory')}</span></div><div><strong>{selected.latency_ms.toFixed(0)} ms</strong><span>{t('latency')}</span></div></div>{metrics.length ? <LineChart values={metrics.map(item => item.latency_ms)} secondary={metrics.map(item => item.packet_loss_percent)} /> : <Empty t={t}/>}</section></div></Modal>}
    {pending && <Confirm t={t} title={`${pending.node.node_key} · ${t(pending.action as 'benchmark'|'restart'|'drain'|'rollback'|'remove')}`} destructive={pending.destructive} onClose={() => setPending(null)} onConfirm={execute}/>} 
  </>
}

export function RoutesPage({ t, locale, notify, routes, nodes, reload }: Common & { routes: Route[]; nodes: Node[]; reload: () => Promise<void> }) {
  const [showCreate, setShowCreate] = useState(false)
  const [activate, setActivate] = useState<Route | null>(null)
  async function create(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget)
    try { await api.createRoute({ name: String(form.get('name')), node_keys: form.getAll('node_keys').map(String), core: String(form.get('core')), protocol: String(form.get('protocol')), transport: String(form.get('transport')), config: {} }); notify(t('completed')); setShowCreate(false); await reload() } catch (error) { notify(error instanceof Error ? error.message : t('failed'), 'error') }
  }
  return <>
    <Panel title={t('trafficEngineering')} eyebrow="ROUTING" className="page-panel" action={<button className="button primary" onClick={() => setShowCreate(true)}><Icon name="plus" size={15}/>{t('createRoute')}</button>}>
      <div className="table-scroll"><table><thead><tr><th>{t('name')}</th><th>{t('protocol')}</th><th>{t('transport')}</th><th>{t('core')}</th><th>{t('path')}</th><th>{t('status')}</th><th>{t('score')}</th><th>{t('wins')}</th><th>{t('updated')}</th><th>{t('actions')}</th></tr></thead><tbody>{routes.map(route => <tr key={route.id}><td><strong>{route.name}</strong>{route.is_golden && <small className="gold-mark">GOLDEN</small>}</td><td><span className="mono-pill">{route.protocol}</span></td><td>{route.transport}</td><td>{route.core}</td><td><div className="route-path">{route.node_keys.map(key => <span key={key}>{key}</span>)}</div></td><td><Badge value={route.status}/></td><td><span className="score-value">{route.score.toFixed(1)}</span></td><td>{route.consecutive_wins}</td><td>{ago(route.updated_at, locale)}</td><td>{route.is_active ? <span className="active-label"><Icon name="check" size={14}/>{t('active')}</span> : <button className="table-button" onClick={() => setActivate(route)}>{t('activate')}</button>}</td></tr>)}</tbody></table></div>{!routes.length && <Empty t={t}/>} 
    </Panel>
    {showCreate && <Modal title={t('createRoute')} onClose={() => setShowCreate(false)}><form className="modal-body form-grid" onSubmit={create}><Field label={t('name')} className="span-2"><input name="name" minLength={2} required autoFocus/></Field><Field label={t('core')}><select name="core"><option>xray</option><option>sing-box</option></select></Field><Field label={t('protocol')}><select name="protocol">{['vless','vmess','trojan','shadowsocks','hysteria2'].map(value => <option key={value}>{value}</option>)}</select></Field><Field label={t('transport')}><select name="transport">{['tcp','grpc','websocket','httpupgrade','xhttp','quic'].map(value => <option key={value}>{value}</option>)}</select></Field><Field label={t('nodesAssigned')} className="span-2"><div className="check-grid">{nodes.map(node => <label key={node.id}><input type="checkbox" name="node_keys" value={node.node_key}/><span>{node.node_key}</span></label>)}</div></Field><div className="form-actions span-2"><button type="button" className="button ghost" onClick={() => setShowCreate(false)}>{t('cancel')}</button><button className="button primary">{t('create')}</button></div></form></Modal>}
    {activate && <Confirm t={t} title={`${t('activate')} · ${activate.name}`} onClose={() => setActivate(null)} onConfirm={async () => { try { await api.activateRoute(activate.id); notify(t('completed')); await reload() } catch (error) { notify(error instanceof Error ? error.message : t('failed'), 'error') } }}/>} 
  </>
}

export function ProtocolsPage({ t, routes }: Common & { routes: Route[] }) {
  const protocols = useMemo(() => Object.entries(routes.reduce<Record<string, Route[]>>((result, route) => { (result[route.protocol] ??= []).push(route); return result }, {})), [routes])
  return <Panel title={t('protocolInventory')} eyebrow="TRANSPORT MATRIX" className="page-panel"><div className="protocol-grid">{protocols.map(([name, items]) => { const avg = items.reduce((sum, item) => sum + item.score, 0) / items.length; return <article className="protocol-card" key={name}><header><span className="protocol-icon"><Icon name="protocols"/></span><div><h3>{name}</h3><span>{[...new Set(items.map(item => item.transport))].join(' · ')}</span></div><Badge value={items.some(item => item.is_active) ? 'ACTIVE' : 'AVAILABLE'}/></header><div className="protocol-stats"><div><span>{t('routesCount')}</span><strong>{items.length}</strong></div><div><span>{t('averageScore')}</span><strong>{avg.toFixed(1)}</strong></div><div><span>{t('bestScore')}</span><strong>{Math.max(...items.map(item => item.score)).toFixed(1)}</strong></div></div></article>})}</div>{!protocols.length && <Empty t={t}/>}</Panel>
}

export function ExperimentsPage({ t, locale, notify }: Common) {
  const [items, setItems] = useState<Experiment[]>([]); const [loading, setLoading] = useState(true)
  const load = async () => { try { setItems(await api.experiments()) } catch (error) { notify(error instanceof Error ? error.message : t('failed'), 'error') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  return <Panel title={t('experimentMemory')} eyebrow="RESEARCH" className="page-panel" action={<div className="memory-summary">{['GOLDEN','VERIFIED','EXPERIMENTAL'].map(level => <span key={level}><i className={level.toLowerCase()}/>{items.filter(item => item.level === level).length} {level}</span>)}</div>}>
    {loading ? <div className="loading"><Spinner/></div> : <><div className="table-scroll"><table><thead><tr><th>{t('candidate')}</th><th>{t('level')}</th><th>{t('protocol')}</th><th>{t('score')}</th><th>{t('latency')}</th><th>{t('loss')}</th><th>{t('throughput')}</th><th>{t('stability')}</th><th>{t('decision')}</th><th>{t('created')}</th><th>{t('actions')}</th></tr></thead><tbody>{items.map(item => <tr key={item.id}><td><code>{item.candidate_id}</code></td><td><Badge value={item.level}/></td><td>{item.protocol} · {item.transport}</td><td><span className="score-value">{item.score.toFixed(1)}</span></td><td>{item.latency_ms.toFixed(0)} ms</td><td>{item.packet_loss_percent.toFixed(2)}%</td><td>{item.throughput_mbps.toFixed(1)} Mbps</td><td>{item.stability_percent.toFixed(1)}%</td><td><Badge value={item.decision}/></td><td>{formatDate(item.created_at, locale)}</td><td><select className="compact-select" value={item.level} onChange={async event => { try { await api.promoteExperiment(item.id, event.target.value); notify(t('completed')); await load() } catch (error) { notify(error instanceof Error ? error.message : t('failed'), 'error') } }}>{['EXPERIMENTAL','VERIFIED','GOLDEN'].map(level => <option key={level}>{level}</option>)}</select></td></tr>)}</tbody></table></div>{!items.length && <Empty t={t}/>}</>}
  </Panel>
}

export function OptimizerPage({ t, notify, dashboard }: Common & { dashboard: Dashboard }) {
  const [decisions, setDecisions] = useState<Decision[]>([]); const [candidates, setCandidates] = useState<Candidate[]>([]); const [running, setRunning] = useState(false)
  const load = async () => { const [decisionRows, candidateRows] = await Promise.all([api.decisions(), api.candidates()]); setDecisions(decisionRows); setCandidates(candidateRows.candidates) }
  useEffect(() => { void load().catch(error => notify(error.message, 'error')) }, [])
  async function decide(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setRunning(true); const form = new FormData(event.currentTarget); try { const result = await api.decide({ current_score: Number(form.get('current_score')), previous_score: Number(form.get('previous_score')), anomaly: form.has('anomaly'), new_method: form.has('new_method'), route_failed: form.has('route_failed'), optimization_requested: true, current_route: {}, candidates }); notify(`${result.action}: ${result.reason}`); await load() } catch (error) { notify(error instanceof Error ? error.message : t('failed'), 'error') } finally { setRunning(false) } }
  const aiCalls = decisions.filter(item => item.ai_called).length
  return <div className="optimizer-layout"><Panel title={t('decisionGateway')} eyebrow="SAFE OPTIMIZATION" className="optimizer-control"><div className="optimizer-state"><div className="ai-orbit"><Icon name="optimizer" size={30}/><span className={dashboard.ai_status === 'DISABLED' ? 'off' : ''}/></div><div><Badge value={dashboard.ai_status}/><h3>{dashboard.mode}</h3></div></div><form className="optimizer-form" onSubmit={decide}><div className="score-inputs"><Field label={t('currentScore')}><input type="number" name="current_score" min="0" max="100" step=".1" defaultValue={dashboard.network_health || 90} required/></Field><Field label={t('previousScore')}><input type="number" name="previous_score" min="0" max="100" step=".1" defaultValue={dashboard.network_health || 90} required/></Field></div><div className="toggle-list">{[['anomaly','anomaly'],['new_method','newMethod'],['route_failed','routeFailed']] .map(([name, key]) => <label key={name}><span>{t(key as 'anomaly'|'newMethod'|'routeFailed')}</span><input type="checkbox" name={name}/><i/></label>)}</div><button className="button primary wide" disabled={running}>{running ? <Spinner/> : <Icon name="optimizer" size={16}/>} {t('runOptimization')}</button></form></Panel>
    <div className="optimizer-main"><div className="metric-grid mini"><MetricCard label={t('candidate')} value={candidates.length} hint={dashboard.mode} icon="experiments"/><MetricCard label={t('aiCalls')} value={aiCalls} hint={`${decisions.length} total`} tone="violet" icon="optimizer"/><MetricCard label={t('localDecisions')} value={decisions.length - aiCalls} hint="store=false" tone="green" icon="check"/></div><Panel title={t('decisionHistory')} eyebrow="MEMORY"><div className="decision-list">{decisions.map(item => <article key={item.id}><div><Badge value={item.action}/><span>{formatDate(item.created_at)}</span></div><strong>{item.current_score.toFixed(1)} <span>→</span> {item.proposed_score.toFixed(1)}</strong><p>{item.reason}</p><footer><code>{item.candidate_id ?? 'LOCAL-RULE'}</code><span>{item.ai_called ? `${item.input_tokens + item.output_tokens} ${t('tokens')}` : 'NO AI CALL'}</span></footer></article>)}</div>{!decisions.length && <Empty t={t}/>}</Panel></div>
  </div>
}

export function UsersPage({ t, locale, notify }: Common) {
  const [users, setUsers] = useState<User[]>([]); const [showCreate, setShowCreate] = useState(false); const [loading, setLoading] = useState(true)
  const load = async () => { try { setUsers(await api.users()) } catch (error) { notify(error instanceof Error ? error.message : t('failed'), 'error') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api.createUser({ username: form.get('username'), email: form.get('email') || null, password: form.get('password'), role: form.get('role'), is_active: true }); notify(t('completed')); setShowCreate(false); await load() } catch (error) { notify(error instanceof Error ? error.message : t('failed'), 'error') } }
  return <><Panel title={t('userManagement')} eyebrow="RBAC" className="page-panel" action={<button className="button primary" onClick={() => setShowCreate(true)}><Icon name="plus" size={15}/>{t('createUser')}</button>}>{loading ? <div className="loading"><Spinner/></div> : <><div className="table-scroll"><table><thead><tr><th>{t('user')}</th><th>{t('email')}</th><th>{t('role')}</th><th>{t('status')}</th><th>{t('created')}</th><th>{t('lastSeen')}</th><th>{t('actions')}</th></tr></thead><tbody>{users.map(user => <tr key={user.id}><td><div className="identity"><span className="user-avatar">{user.username.slice(0,2).toUpperCase()}</span><strong>{user.username}</strong></div></td><td>{user.email ?? '—'}</td><td><span className="role-pill">{user.role.replaceAll('_',' ')}</span></td><td><Badge value={user.is_active ? 'ENABLED' : 'DISABLED'}/></td><td>{formatDate(user.created_at, locale)}</td><td>{ago(user.last_login_at, locale)}</td><td><label className="switch"><input type="checkbox" checked={user.is_active} onChange={async event => { try { await api.updateUser(user.id, { is_active: event.target.checked }); await load() } catch (error) { notify(error instanceof Error ? error.message : t('failed'), 'error') } }}/><i/></label></td></tr>)}</tbody></table></div>{!users.length && <Empty t={t}/>}</>}</Panel>{showCreate && <Modal title={t('createUser')} onClose={() => setShowCreate(false)}><form className="modal-body form-grid" onSubmit={create}><Field label={t('username')}><input name="username" minLength={3} required autoFocus/></Field><Field label={t('email')}><input name="email" type="email"/></Field><Field label={t('password')} className="span-2"><input name="password" type="password" minLength={12} required/></Field><Field label={t('role')} className="span-2"><select name="role">{['SUPER_ADMIN','ADMIN','OPERATOR','RESELLER','USER'].map(role => <option key={role}>{role}</option>)}</select></Field><div className="form-actions span-2"><button type="button" className="button ghost" onClick={() => setShowCreate(false)}>{t('cancel')}</button><button className="button primary">{t('create')}</button></div></form></Modal>}</>
}

export function SubscriptionsPage({ t, locale, notify }: Common) {
  const [items, setItems] = useState<Subscription[]>([]); const [users, setUsers] = useState<User[]>([]); const [plans, setPlans] = useState<Plan[]>([]); const [nodes, setNodes] = useState<Node[]>([]); const [showCreate, setShowCreate] = useState(false); const [token, setToken] = useState('')
  const load = async () => { const [subscriptions, userRows, planRows, nodeRows] = await Promise.all([api.subscriptions(), api.users().catch(() => []), api.plans(), api.nodes()]); setItems(subscriptions); setUsers(userRows); setPlans(planRows); setNodes(nodeRows) }
  useEffect(() => { void load().catch(error => notify(error.message, 'error')) }, [])
  const userName = (id: number) => users.find(user => user.id === id)?.username ?? `#${id}`; const planName = (id: number) => plans.find(plan => plan.id === id)?.name ?? `#${id}`
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { const result = await api.createSubscription({ user_id: Number(form.get('user_id')), plan_id: Number(form.get('plan_id')), node_keys: form.getAll('node_keys').map(String) }); setToken(result.token); setShowCreate(false); await load() } catch (error) { notify(error instanceof Error ? error.message : t('failed'), 'error') } }
  return <><Panel title={t('subscriptionManagement')} eyebrow="ACCESS" className="page-panel" action={<button className="button primary" onClick={() => setShowCreate(true)}><Icon name="plus" size={15}/>{t('createSubscription')}</button>}><div className="table-scroll"><table><thead><tr><th>ID</th><th>{t('user')}</th><th>{t('plan')}</th><th>{t('status')}</th><th>{t('usage')}</th><th>{t('nodesAssigned')}</th><th>{t('expires')}</th></tr></thead><tbody>{items.map(item => { const plan = plans.find(value => value.id === item.plan_id); const percent = plan?.quota_gb ? item.used_gb / plan.quota_gb * 100 : 0; return <tr key={item.id}><td><code>SUB-{item.id}</code></td><td><strong>{userName(item.user_id)}</strong></td><td>{planName(item.plan_id)}</td><td><Badge value={item.enabled ? 'ACTIVE' : 'DISABLED'}/></td><td><div className="usage-cell"><Progress value={percent}/><span>{item.used_gb.toFixed(1)} / {plan?.quota_gb ?? 0} GB</span></div></td><td><div className="route-path">{item.node_keys.map(key => <span key={key}>{key}</span>)}</div></td><td>{formatDate(item.expires_at, locale)}</td></tr>})}</tbody></table></div>{!items.length && <Empty t={t}/>}</Panel>{showCreate && <Modal title={t('createSubscription')} onClose={() => setShowCreate(false)}><form className="modal-body form-grid" onSubmit={create}><Field label={t('user')}><select name="user_id" required>{users.map(user => <option key={user.id} value={user.id}>{user.username}</option>)}</select></Field><Field label={t('plan')}><select name="plan_id" required>{plans.map(plan => <option key={plan.id} value={plan.id}>{plan.name}</option>)}</select></Field><Field label={t('nodesAssigned')} className="span-2"><div className="check-grid">{nodes.map(node => <label key={node.id}><input type="checkbox" name="node_keys" value={node.node_key}/><span>{node.node_key}</span></label>)}</div></Field><div className="form-actions span-2"><button type="button" className="button ghost" onClick={() => setShowCreate(false)}>{t('cancel')}</button><button className="button primary">{t('create')}</button></div></form></Modal>}{token && <Modal title={t('completed')} onClose={() => setToken('')}><div className="modal-body"><p className="muted">{t('revealOnce')}</p><div className="secret-value"><code>{token}</code><button onClick={() => void navigator.clipboard.writeText(token)}><Icon name="copy"/></button></div></div></Modal>}</>
}

export function BillingPage({ t, notify }: Common) {
  const [plans, setPlans] = useState<Plan[]>([]); const [showCreate, setShowCreate] = useState(false)
  const load = async () => setPlans(await api.plans()); useEffect(() => { void load().catch(error => notify(error.message, 'error')) }, [])
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await api.createPlan({ name: form.get('name'), quota_gb: Number(form.get('quota_gb')), duration_days: Number(form.get('duration_days')), max_devices: Number(form.get('max_devices')), price_minor: Number(form.get('price_minor')) }); notify(t('completed')); setShowCreate(false); await load() } catch (error) { notify(error instanceof Error ? error.message : t('failed'), 'error') } }
  return <><Panel title={t('plans')} eyebrow="BILLING" className="page-panel" action={<button className="button primary" onClick={() => setShowCreate(true)}><Icon name="plus" size={15}/>{t('createPlan')}</button>}><div className="plans-grid">{plans.map(plan => <article className="plan-card" key={plan.id}><header><Badge value={plan.enabled ? 'ACTIVE' : 'DISABLED'}/><span>#{plan.id}</span></header><h3>{plan.name}</h3><strong>{plan.price_minor.toLocaleString()}</strong><span className="price-unit">minor units / {plan.duration_days} {t('days')}</span><div className="plan-features"><div><span>{t('quota')}</span><b>{plan.quota_gb} GB</b></div><div><span>{t('duration')}</span><b>{plan.duration_days} {t('days')}</b></div><div><span>{t('devices')}</span><b>{plan.max_devices}</b></div></div></article>)}</div>{!plans.length && <Empty t={t}/>}</Panel>{showCreate && <Modal title={t('createPlan')} onClose={() => setShowCreate(false)}><form className="modal-body form-grid" onSubmit={create}><Field label={t('name')} className="span-2"><input name="name" minLength={2} required autoFocus/></Field><Field label={`${t('quota')} (GB)`}><input name="quota_gb" type="number" min="0" step=".1" required/></Field><Field label={t('duration')}><input name="duration_days" type="number" min="1" defaultValue="30" required/></Field><Field label={t('devices')}><input name="max_devices" type="number" min="1" defaultValue="1" required/></Field><Field label={t('price')}><input name="price_minor" type="number" min="0" required/></Field><div className="form-actions span-2"><button type="button" className="button ghost" onClick={() => setShowCreate(false)}>{t('cancel')}</button><button className="button primary">{t('create')}</button></div></form></Modal>}</>
}

export function SettingsPage({ t, locale, notify }: Common) {
  const [tab, setTab] = useState<'runtime'|'security'|'audit'>('runtime'); const [settings, setSettings] = useState<SystemSetting[]>([]); const [national, setNational] = useState<NationalMode | null>(null); const [audit, setAudit] = useState<AuditLog[]>([]); const [keyName, setKeyName] = useState(''); const [secret, setSecret] = useState('')
  useEffect(() => { void Promise.all([api.settings().catch(() => []), api.nationalMode(), api.auditLogs().catch(() => [])]).then(([settingRows, state, auditRows]) => { setSettings(settingRows); setNational(state); setAudit(auditRows) }).catch(error => notify(error.message, 'error')) }, [])
  async function update(key: string, value: string) { try { await api.updateSetting(key, value); notify(t('completed')); setSettings(await api.settings()) } catch (error) { notify(error instanceof Error ? error.message : t('failed'), 'error') } }
  return <Panel title={t('systemSettings')} eyebrow="CONTROL PLANE" className="page-panel"><div className="settings-tabs">{(['runtime','security','audit'] as const).map(value => <button key={value} className={tab === value ? 'active' : ''} onClick={() => setTab(value)}>{t(value)}</button>)}</div>{tab === 'runtime' && <div className="settings-layout"><section className="settings-section"><h3>{t('nationalMode')}</h3><div className="setting-row"><div><span>{t('status')}</span><small>{national?.mode ?? '—'}</small></div>{national && <Badge value={national.mode}/>}</div><div className="setting-row"><div><span>{t('internationalFailures')}</span><small>{national?.failures ?? 0}</small></div><strong>{national?.failures ?? 0}</strong></div><div className="setting-row"><div><span>{t('internationalSuccesses')}</span><small>{national?.successes ?? 0}</small></div><strong>{national?.successes ?? 0}</strong></div></section><section className="settings-section"><h3>{t('optimizer')}</h3><div className="setting-row"><div><span>{t('optimizerEnabled')}</span><small>optimizer.enabled</small></div><button className="button subtle" onClick={() => void update('optimizer.enabled','true')}>{t('enabled')}</button></div><div className="setting-row"><div><span>{t('minScoreChange')}</span><small>optimizer.min_score_change</small></div><button className="button subtle" onClick={() => void update('optimizer.min_score_change','3.0')}>3.0</button></div>{settings.map(row => <div className="setting-row" key={row.key}><div><span>{row.key}</span><small>{formatDate(row.updated_at, locale)}</small></div><Badge value={row.is_secret ? 'SECRET' : 'CONFIG'}/></div>)}</section></div>}{tab === 'security' && <div className="settings-layout single"><section className="settings-section"><h3>{t('createApiKey')}</h3><div className="api-key-form"><input value={keyName} onChange={event => setKeyName(event.target.value)} placeholder={t('keyName')}/><button className="button primary" disabled={!keyName.trim()} onClick={async () => { try { const result = await api.createApiKey(keyName, []); setSecret(result.key); setKeyName('') } catch (error) { notify(error instanceof Error ? error.message : t('failed'), 'error') } }}>{t('create')}</button></div>{secret && <div className="secret-value"><code>{secret}</code><button onClick={() => void navigator.clipboard.writeText(secret)}><Icon name="copy"/></button></div>}</section></div>}{tab === 'audit' && <div className="table-scroll"><table><thead><tr><th>{t('created')}</th><th>{t('actor')}</th><th>{t('actions')}</th><th>{t('resource')}</th><th>{t('ipAddress')}</th></tr></thead><tbody>{audit.map(row => <tr key={row.id}><td>{formatDate(row.created_at, locale)}</td><td>{row.actor_user_id ? `#${row.actor_user_id}` : 'SYSTEM'}</td><td><code>{row.action}</code></td><td>{row.resource_type} · {row.resource_id}</td><td><code>{row.ip_address || '—'}</code></td></tr>)}</tbody></table>{!audit.length && <Empty t={t}/>}</div>}</Panel>
}
