import { useEffect, useState } from 'react'
import { api } from './api'
import { Empty, Field, Icon, Modal, Panel, type T } from './ui'

type Inbound = { id:number; name:string; node_key:string; core:string; protocol:string; port:number; transport:string; security:string; score:number; status:string; is_selected:boolean }
type Client = { id:number; name:string; email?:string|null; uuid:string; inbound_ids:number[]; configs:Array<{ inbound_id:number; protocol:string; link:string; note?:string }> }

export function TrafficUsersPage({ t, notify }: { t:T; notify:(message:string, kind?:'success'|'error')=>void }) {
  const [inbounds,setInbounds]=useState<Inbound[]>([]); const [clients,setClients]=useState<Client[]>([]); const [show,setShow]=useState(false); const [selected,setSelected]=useState<Client|null>(null); const [loading,setLoading]=useState(true)
  async function load(){ try { const [i,c]=await Promise.all([api.inbounds(),api.clientUsers()]); setInbounds(i); setClients(c) } catch(e){ notify(e instanceof Error?e.message:t('failed'),'error') } finally { setLoading(false) } }
  useEffect(()=>{void load()},[])
  async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const ids=f.getAll('inbound_ids').map(Number);try{const result=await api.createClientUser({name:String(f.get('name')),email:String(f.get('email')||''),inbound_ids:ids});notify(t('completed'));setShow(false);setSelected(result);await load()}catch(e){notify(e instanceof Error?e.message:t('failed'),'error')}}
  async function remove(id:number){try{await api.deleteClientUser(id);notify(t('completed'));setSelected(null);await load()}catch(e){notify(e instanceof Error?e.message:t('failed'),'error')}}
  return <div className="dashboard-grid"><Panel title="Users" eyebrow="CLIENT PROFILES" className="wide-panel" action={<button className="button primary" onClick={()=>setShow(true)}><Icon name="plus" size={15}/>Create user</button>}>
    <div className="table-scroll"><table><thead><tr><th>Name</th><th>Email</th><th>UUID</th><th>Inbounds</th><th>Configs</th><th>Actions</th></tr></thead><tbody>{clients.map(c=><tr key={c.id}><td><strong>{c.name}</strong></td><td>{c.email||'—'}</td><td><code>{c.uuid}</code></td><td>{c.inbound_ids.length}</td><td>{c.configs.length}</td><td><button className="table-button" onClick={()=>setSelected(c)}>View configs</button></td></tr>)}</tbody></table></div>{!clients.length&&!loading&&<Empty t={t}/>}</Panel>
    <Panel title="Available inbounds" eyebrow="NODE + AI OUTPUT" className="wide-panel"><div className="table-scroll"><table><thead><tr><th>Name</th><th>Node</th><th>Protocol</th><th>Transport</th><th>Security</th><th>Score</th><th>Status</th></tr></thead><tbody>{inbounds.map(i=><tr key={i.id}><td><strong>{i.name}</strong></td><td>{i.node_key}</td><td>{i.protocol}</td><td>{i.transport}</td><td>{i.security}</td><td>{i.score}</td><td>{i.status}</td></tr>)}</tbody></table></div>{!inbounds.length&&!loading&&<Empty t={t}/>}</Panel>
    {show&&<Modal title="Create user" onClose={()=>setShow(false)}><form className="modal-body form-grid" onSubmit={create}><Field label="Name"><input name="name" required autoFocus/></Field><Field label="Email"><input name="email" type="email"/></Field><Field label="Inbounds" className="span-2"><div className="check-grid">{inbounds.map(i=><label key={i.id}><input type="checkbox" name="inbound_ids" value={i.id}/><span>{i.name} · {i.protocol} · {i.node_key}</span></label>)}</div></Field><div className="form-actions span-2"><button type="button" className="button ghost" onClick={()=>setShow(false)}>Cancel</button><button className="button primary">Create</button></div></form></Modal>}
    {selected&&<Modal title={`${selected.name} · configs`} onClose={()=>setSelected(null)} wide><div className="detail-list">{selected.configs.map(c=><div key={c.inbound_id}><span>{c.protocol} · inbound {c.inbound_id}</span><code>{c.link||c.note||'—'}</code></div>)}</div><div className="form-actions"><button className="button ghost" onClick={()=>setSelected(null)}>Close</button><button className="button danger" onClick={()=>void remove(selected.id)}>Delete user</button></div></Modal>}
  </div>
}
