import { useEffect, useState } from 'react'
import { api } from './api'
import { Empty, Field, Icon, Modal, Panel, type T } from './ui'

type UserRow={id:number;username:string;email?:string|null;role:string;is_active:boolean;quota_gb:number;used_gb:number;expires_at:string|null;plan_id:number|null;subscription_token?:string|null}
export function TrafficUsersPage({t,notify}:{t:T;notify:(message:string,kind?:'success'|'error')=>void}){
 const [users,setUsers]=useState<UserRow[]>([]);const [show,setShow]=useState(false);const [selected,setSelected]=useState<UserRow|null>(null);const [loading,setLoading]=useState(true)
 async function load(){try{setUsers(await api.users() as UserRow[])}catch(e){notify(e instanceof Error?e.message:t('failed'),'error')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 async function create(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const quota=Number(f.get('quota_gb')||0);const days=Number(f.get('duration_days')||0);try{const result=await api.createUser({username:String(f.get('username')),email:String(f.get('email')||''),password:String(f.get('password')),role:'USER',is_active:true,node_keys:[],quota_gb:quota,duration_days:days});notify(t('completed'));setShow(false);setSelected(result as UserRow);await load()}catch(e){notify(e instanceof Error?e.message:t('failed'),'error')}}
 function formatQuota(u:UserRow){return u.quota_gb===0?'Unlimited':`${u.used_gb.toFixed(2)} / ${u.quota_gb} GB`}
 function formatExpiry(u:UserRow){return u.expires_at?new Date(u.expires_at).toLocaleString():'Unlimited'}
 return <div className="dashboard-grid"><Panel title="Users" eyebrow="USER PROFILES" className="wide-panel" action={<button className="button primary" onClick={()=>setShow(true)}><Icon name="plus" size={15}/>Create user</button>}><div className="table-scroll"><table><thead><tr><th>Username</th><th>Role</th><th>Traffic</th><th>Expires</th><th>Status</th><th>Actions</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><strong>{u.username}</strong><br/><small>{u.email||'—'}</small></td><td>{u.role}</td><td>{formatQuota(u)}</td><td>{formatExpiry(u)}</td><td>{u.is_active?'Active':'Disabled'}</td><td><button className="table-button" onClick={()=>setSelected(u)}>Details</button></td></tr>)}</tbody></table></div>{!users.length&&!loading&&<Empty t={t}/>}</Panel>{show&&<Modal title="Create user" onClose={()=>setShow(false)}><form className="modal-body form-grid" onSubmit={create}><Field label="Username"><input name="username" required autoFocus/></Field><Field label="Email"><input name="email" type="email"/></Field><Field label="Password"><input name="password" type="password" minLength={12} required/></Field><Field label="Traffic (GB)"><input name="quota_gb" type="number" min="0" step="0.01" defaultValue="0"/><small>0 = unlimited</small></Field><Field label="Duration (days)"><input name="duration_days" type="number" min="0" defaultValue="0"/><small>0 = unlimited</small></Field><div className="form-actions span-2"><button type="button" className="button ghost" onClick={()=>setShow(false)}>Cancel</button><button className="button primary">Create</button></div></form></Modal>}{selected&&<Modal title={`${selected.username} · details`} onClose={()=>setSelected(null)}><div className="detail-list"><div><span>Traffic</span><strong>{formatQuota(selected)}</strong></div><div><span>Expiration</span><strong>{formatExpiry(selected)}</strong></div><div><span>Inbound</span><strong>Optional</strong></div><div><span>Subscription</span><code>{selected.subscription_token||'Generated'}</code></div></div><div className="form-actions"><button className="button ghost" onClick={()=>setSelected(null)}>Close</button></div></Modal>}</div>
}
